development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: <%= ENV.fetch("redis://h:pe4c19b1d8a7a5b19040ea78f1409176321d18a3866f33ef4dc9c36c5ce9c96be@ec2-52-54-229-237.compute-1.amazonaws.com:13049") { "redis://localhost:6379/1" } %>
  channel_prefix: message_me_production
